### PR TITLE
Update test app UI to add Feedback button

### PR DESCRIPTION
**Pull request by max-lobanov**
- Update test app UI to add one more button to open feedback window
- Modify UI: decrease top offset to fit button to the screen
image

### CODE REVIEW

**Comment by SergeySmolin** [comment]
Why is Check For Update button used 2 times? Maybe we should remove one of them?

**Comment by max-lobanov** [comment]
> Why is Check For Update button used 2 times? Maybe we should remove one of them?
I don't have idea.
It looks like they invoke the same code and one of them can be removed.
@MatkovIvan @ElektrojungeMS , Could you please confirm it?

**Comment by MatkovIvan** [comment]
@max-lobanov Please remove it. I've noticed that I introduced this duplicated code
qhumbo8yhug

**Comment by max-lobanov** [comment]
> @max-lobanov Please remove it. I've noticed that I introduced this duplicated code

Fixed!

**Pull request merged**
